name: Python Package CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort pylint pydocstyle pytest pytest-cov build
        pip install -r requirements.txt
        pip install -e .
    
    - name: Run Black
      run: black . --check
    
    - name: Run isort
      run: isort . --check
    
    - name: Run Pylint
      run: pylint src tests
    
    - name: Run pydocstyle
      run: pydocstyle src
    
    - name: Run tests with coverage
      run: pytest tests/ --cov=src --cov-report=xml
    
    - name: Build package
      run: python -m build